/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing AssetIssueRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetIssueRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetIssueRequest
        //private AssetIssueRequest instance;

        public AssetIssueRequestTests()
        {
            // TODO uncomment below to create an instance of AssetIssueRequest
            //instance = new AssetIssueRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetIssueRequest
        /// </summary>
        [Fact]
        public void AssetIssueRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetIssueRequest
            //Assert.IsType<AssetIssueRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ErgValue'
        /// </summary>
        [Fact]
        public void ErgValueTest()
        {
            // TODO unit test for the property 'ErgValue'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Decimals'
        /// </summary>
        [Fact]
        public void DecimalsTest()
        {
            // TODO unit test for the property 'Decimals'
        }
        /// <summary>
        /// Test the property 'Registers'
        /// </summary>
        [Fact]
        public void RegistersTest()
        {
            // TODO unit test for the property 'Registers'
        }

    }

}
