/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing BlacklistedPeers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlacklistedPeersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlacklistedPeers
        //private BlacklistedPeers instance;

        public BlacklistedPeersTests()
        {
            // TODO uncomment below to create an instance of BlacklistedPeers
            //instance = new BlacklistedPeers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlacklistedPeers
        /// </summary>
        [Fact]
        public void BlacklistedPeersInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlacklistedPeers
            //Assert.IsType<BlacklistedPeers>(instance);
        }


        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Fact]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }

    }

}
