/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing BlockADProofs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockADProofsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockADProofs
        //private BlockADProofs instance;

        public BlockADProofsTests()
        {
            // TODO uncomment below to create an instance of BlockADProofs
            //instance = new BlockADProofs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockADProofs
        /// </summary>
        [Fact]
        public void BlockADProofsInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockADProofs
            //Assert.IsType<BlockADProofs>(instance);
        }


        /// <summary>
        /// Test the property 'HeaderId'
        /// </summary>
        [Fact]
        public void HeaderIdTest()
        {
            // TODO unit test for the property 'HeaderId'
        }
        /// <summary>
        /// Test the property 'ProofBytes'
        /// </summary>
        [Fact]
        public void ProofBytesTest()
        {
            // TODO unit test for the property 'ProofBytes'
        }
        /// <summary>
        /// Test the property 'Digest'
        /// </summary>
        [Fact]
        public void DigestTest()
        {
            // TODO unit test for the property 'Digest'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

    }

}
