/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing BoxesRequestHolder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoxesRequestHolderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BoxesRequestHolder
        //private BoxesRequestHolder instance;

        public BoxesRequestHolderTests()
        {
            // TODO uncomment below to create an instance of BoxesRequestHolder
            //instance = new BoxesRequestHolder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BoxesRequestHolder
        /// </summary>
        [Fact]
        public void BoxesRequestHolderInstanceTest()
        {
            // TODO uncomment below to test "IsType" BoxesRequestHolder
            //Assert.IsType<BoxesRequestHolder>(instance);
        }


        /// <summary>
        /// Test the property 'TargetAssets'
        /// </summary>
        [Fact]
        public void TargetAssetsTest()
        {
            // TODO unit test for the property 'TargetAssets'
        }
        /// <summary>
        /// Test the property 'TargetBalance'
        /// </summary>
        [Fact]
        public void TargetBalanceTest()
        {
            // TODO unit test for the property 'TargetBalance'
        }

    }

}
