/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing CandidateBlock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CandidateBlockTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CandidateBlock
        //private CandidateBlock instance;

        public CandidateBlockTests()
        {
            // TODO uncomment below to create an instance of CandidateBlock
            //instance = new CandidateBlock();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CandidateBlock
        /// </summary>
        [Fact]
        public void CandidateBlockInstanceTest()
        {
            // TODO uncomment below to test "IsType" CandidateBlock
            //Assert.IsType<CandidateBlock>(instance);
        }


        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'ExtensionHash'
        /// </summary>
        [Fact]
        public void ExtensionHashTest()
        {
            // TODO unit test for the property 'ExtensionHash'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'StateRoot'
        /// </summary>
        [Fact]
        public void StateRootTest()
        {
            // TODO unit test for the property 'StateRoot'
        }
        /// <summary>
        /// Test the property 'NBits'
        /// </summary>
        [Fact]
        public void NBitsTest()
        {
            // TODO unit test for the property 'NBits'
        }
        /// <summary>
        /// Test the property 'AdProofBytes'
        /// </summary>
        [Fact]
        public void AdProofBytesTest()
        {
            // TODO unit test for the property 'AdProofBytes'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'TransactionsNumber'
        /// </summary>
        [Fact]
        public void TransactionsNumberTest()
        {
            // TODO unit test for the property 'TransactionsNumber'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'Votes'
        /// </summary>
        [Fact]
        public void VotesTest()
        {
            // TODO unit test for the property 'Votes'
        }

    }

}
