/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing CommitmentWithSecret
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommitmentWithSecretTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommitmentWithSecret
        //private CommitmentWithSecret instance;

        public CommitmentWithSecretTests()
        {
            // TODO uncomment below to create an instance of CommitmentWithSecret
            //instance = new CommitmentWithSecret();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommitmentWithSecret
        /// </summary>
        [Fact]
        public void CommitmentWithSecretInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommitmentWithSecret
            //Assert.IsType<CommitmentWithSecret>(instance);
        }


        /// <summary>
        /// Test the property 'Hint'
        /// </summary>
        [Fact]
        public void HintTest()
        {
            // TODO unit test for the property 'Hint'
        }
        /// <summary>
        /// Test the property 'Pubkey'
        /// </summary>
        [Fact]
        public void PubkeyTest()
        {
            // TODO unit test for the property 'Pubkey'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Fact]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }
        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }

    }

}
