/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing DlogCommitment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DlogCommitmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DlogCommitment
        //private DlogCommitment instance;

        public DlogCommitmentTests()
        {
            // TODO uncomment below to create an instance of DlogCommitment
            //instance = new DlogCommitment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DlogCommitment
        /// </summary>
        [Fact]
        public void DlogCommitmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" DlogCommitment
            //Assert.IsType<DlogCommitment>(instance);
        }


        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Fact]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }
        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Fact]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

    }

}
