/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing EmissionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmissionInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmissionInfo
        //private EmissionInfo instance;

        public EmissionInfoTests()
        {
            // TODO uncomment below to create an instance of EmissionInfo
            //instance = new EmissionInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmissionInfo
        /// </summary>
        [Fact]
        public void EmissionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmissionInfo
            //Assert.IsType<EmissionInfo>(instance);
        }


        /// <summary>
        /// Test the property 'MinerReward'
        /// </summary>
        [Fact]
        public void MinerRewardTest()
        {
            // TODO unit test for the property 'MinerReward'
        }
        /// <summary>
        /// Test the property 'TotalCoinsIssued'
        /// </summary>
        [Fact]
        public void TotalCoinsIssuedTest()
        {
            // TODO unit test for the property 'TotalCoinsIssued'
        }
        /// <summary>
        /// Test the property 'TotalRemainCoins'
        /// </summary>
        [Fact]
        public void TotalRemainCoinsTest()
        {
            // TODO unit test for the property 'TotalRemainCoins'
        }

    }

}
