/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing EqualsPredicate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EqualsPredicateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EqualsPredicate
        //private EqualsPredicate instance;

        public EqualsPredicateTests()
        {
            // TODO uncomment below to create an instance of EqualsPredicate
            //instance = new EqualsPredicate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EqualsPredicate
        /// </summary>
        [Fact]
        public void EqualsPredicateInstanceTest()
        {
            // TODO uncomment below to test "IsType" EqualsPredicate
            //Assert.IsType<EqualsPredicate>(instance);
        }


        /// <summary>
        /// Test the property 'Predicate'
        /// </summary>
        [Fact]
        public void PredicateTest()
        {
            // TODO unit test for the property 'Predicate'
        }
        /// <summary>
        /// Test the property 'Register'
        /// </summary>
        [Fact]
        public void RegisterTest()
        {
            // TODO unit test for the property 'Register'
        }
        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Fact]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }

    }

}
