/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing ErgoTransactionOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErgoTransactionOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErgoTransactionOutput
        //private ErgoTransactionOutput instance;

        public ErgoTransactionOutputTests()
        {
            // TODO uncomment below to create an instance of ErgoTransactionOutput
            //instance = new ErgoTransactionOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErgoTransactionOutput
        /// </summary>
        [Fact]
        public void ErgoTransactionOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErgoTransactionOutput
            //Assert.IsType<ErgoTransactionOutput>(instance);
        }


        /// <summary>
        /// Test the property 'BoxId'
        /// </summary>
        [Fact]
        public void BoxIdTest()
        {
            // TODO unit test for the property 'BoxId'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'ErgoTree'
        /// </summary>
        [Fact]
        public void ErgoTreeTest()
        {
            // TODO unit test for the property 'ErgoTree'
        }
        /// <summary>
        /// Test the property 'CreationHeight'
        /// </summary>
        [Fact]
        public void CreationHeightTest()
        {
            // TODO unit test for the property 'CreationHeight'
        }
        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }
        /// <summary>
        /// Test the property 'AdditionalRegisters'
        /// </summary>
        [Fact]
        public void AdditionalRegistersTest()
        {
            // TODO unit test for the property 'AdditionalRegisters'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

    }

}
