/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing Extension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Extension
        //private Extension instance;

        public ExtensionTests()
        {
            // TODO uncomment below to create an instance of Extension
            //instance = new Extension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Extension
        /// </summary>
        [Fact]
        public void ExtensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Extension
            //Assert.IsType<Extension>(instance);
        }


        /// <summary>
        /// Test the property 'HeaderId'
        /// </summary>
        [Fact]
        public void HeaderIdTest()
        {
            // TODO unit test for the property 'HeaderId'
        }
        /// <summary>
        /// Test the property 'Digest'
        /// </summary>
        [Fact]
        public void DigestTest()
        {
            // TODO unit test for the property 'Digest'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

    }

}
