/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing FeeHistogramBin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeeHistogramBinTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeeHistogramBin
        //private FeeHistogramBin instance;

        public FeeHistogramBinTests()
        {
            // TODO uncomment below to create an instance of FeeHistogramBin
            //instance = new FeeHistogramBin();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeeHistogramBin
        /// </summary>
        [Fact]
        public void FeeHistogramBinInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeeHistogramBin
            //Assert.IsType<FeeHistogramBin>(instance);
        }


        /// <summary>
        /// Test the property 'NTxns'
        /// </summary>
        [Fact]
        public void NTxnsTest()
        {
            // TODO unit test for the property 'NTxns'
        }
        /// <summary>
        /// Test the property 'TotalFee'
        /// </summary>
        [Fact]
        public void TotalFeeTest()
        {
            // TODO unit test for the property 'TotalFee'
        }

    }

}
