/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse200
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse200Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200
        //private InlineResponse200 instance;

        public InlineResponse200Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse200
            //instance = new InlineResponse200();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse200
        /// </summary>
        [Fact]
        public void InlineResponse200InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse200
            //Assert.IsType<InlineResponse200>(instance);
        }


        /// <summary>
        /// Test the property 'Mnemonic'
        /// </summary>
        [Fact]
        public void MnemonicTest()
        {
            // TODO unit test for the property 'Mnemonic'
        }

    }

}
