/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing InlineObject2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject2
        //private InlineObject2 instance;

        public InlineObject2Tests()
        {
            // TODO uncomment below to create an instance of InlineObject2
            //instance = new InlineObject2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject2
        /// </summary>
        [Fact]
        public void InlineObject2InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineObject2
            //Assert.IsType<InlineObject2>(instance);
        }


        /// <summary>
        /// Test the property 'Mnemonic'
        /// </summary>
        [Fact]
        public void MnemonicTest()
        {
            // TODO unit test for the property 'Mnemonic'
        }
        /// <summary>
        /// Test the property 'MnemonicPass'
        /// </summary>
        [Fact]
        public void MnemonicPassTest()
        {
            // TODO unit test for the property 'MnemonicPass'
        }

    }

}
