/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2004
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004
        //private InlineResponse2004 instance;

        public InlineResponse2004Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2004
            //instance = new InlineResponse2004();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2004
        /// </summary>
        [Fact]
        public void InlineResponse2004InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2004
            //Assert.IsType<InlineResponse2004>(instance);
        }


        /// <summary>
        /// Test the property 'DerivationPath'
        /// </summary>
        [Fact]
        public void DerivationPathTest()
        {
            // TODO unit test for the property 'DerivationPath'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
