/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing PopowHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PopowHeaderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PopowHeader
        //private PopowHeader instance;

        public PopowHeaderTests()
        {
            // TODO uncomment below to create an instance of PopowHeader
            //instance = new PopowHeader();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PopowHeader
        /// </summary>
        [Fact]
        public void PopowHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsType" PopowHeader
            //Assert.IsType<PopowHeader>(instance);
        }


        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Interlinks'
        /// </summary>
        [Fact]
        public void InterlinksTest()
        {
            // TODO unit test for the property 'Interlinks'
        }

    }

}
