/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing PowSolutions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PowSolutionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PowSolutions
        //private PowSolutions instance;

        public PowSolutionsTests()
        {
            // TODO uncomment below to create an instance of PowSolutions
            //instance = new PowSolutions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PowSolutions
        /// </summary>
        [Fact]
        public void PowSolutionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PowSolutions
            //Assert.IsType<PowSolutions>(instance);
        }


        /// <summary>
        /// Test the property 'Pk'
        /// </summary>
        [Fact]
        public void PkTest()
        {
            // TODO unit test for the property 'Pk'
        }
        /// <summary>
        /// Test the property 'W'
        /// </summary>
        [Fact]
        public void WTest()
        {
            // TODO unit test for the property 'W'
        }
        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Fact]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }
        /// <summary>
        /// Test the property 'D'
        /// </summary>
        [Fact]
        public void DTest()
        {
            // TODO unit test for the property 'D'
        }

    }

}
