/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing PreHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreHeaderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreHeader
        //private PreHeader instance;

        public PreHeaderTests()
        {
            // TODO uncomment below to create an instance of PreHeader
            //instance = new PreHeader();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreHeader
        /// </summary>
        [Fact]
        public void PreHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsType" PreHeader
            //Assert.IsType<PreHeader>(instance);
        }


        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'NBits'
        /// </summary>
        [Fact]
        public void NBitsTest()
        {
            // TODO unit test for the property 'NBits'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'Votes'
        /// </summary>
        [Fact]
        public void VotesTest()
        {
            // TODO unit test for the property 'Votes'
        }
        /// <summary>
        /// Test the property 'MinerPk'
        /// </summary>
        [Fact]
        public void MinerPkTest()
        {
            // TODO unit test for the property 'MinerPk'
        }

    }

}
