/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing ProofOfUpcomingTransactions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProofOfUpcomingTransactionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProofOfUpcomingTransactions
        //private ProofOfUpcomingTransactions instance;

        public ProofOfUpcomingTransactionsTests()
        {
            // TODO uncomment below to create an instance of ProofOfUpcomingTransactions
            //instance = new ProofOfUpcomingTransactions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProofOfUpcomingTransactions
        /// </summary>
        [Fact]
        public void ProofOfUpcomingTransactionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProofOfUpcomingTransactions
            //Assert.IsType<ProofOfUpcomingTransactions>(instance);
        }


        /// <summary>
        /// Test the property 'MsgPreimage'
        /// </summary>
        [Fact]
        public void MsgPreimageTest()
        {
            // TODO unit test for the property 'MsgPreimage'
        }
        /// <summary>
        /// Test the property 'TxProofs'
        /// </summary>
        [Fact]
        public void TxProofsTest()
        {
            // TODO unit test for the property 'TxProofs'
        }

    }

}
