/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing ScanningPredicate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScanningPredicateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScanningPredicate
        //private ScanningPredicate instance;

        public ScanningPredicateTests()
        {
            // TODO uncomment below to create an instance of ScanningPredicate
            //instance = new ScanningPredicate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanningPredicate
        /// </summary>
        [Fact]
        public void ScanningPredicateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScanningPredicate
            //Assert.IsType<ScanningPredicate>(instance);
        }


        /// <summary>
        /// Test the property 'Predicate'
        /// </summary>
        [Fact]
        public void PredicateTest()
        {
            // TODO unit test for the property 'Predicate'
        }

    }

}
