/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing SecretProven
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecretProvenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecretProven
        //private SecretProven instance;

        public SecretProvenTests()
        {
            // TODO uncomment below to create an instance of SecretProven
            //instance = new SecretProven();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecretProven
        /// </summary>
        [Fact]
        public void SecretProvenInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecretProven
            //Assert.IsType<SecretProven>(instance);
        }


        /// <summary>
        /// Test the property 'Hint'
        /// </summary>
        [Fact]
        public void HintTest()
        {
            // TODO unit test for the property 'Hint'
        }
        /// <summary>
        /// Test the property 'Challenge'
        /// </summary>
        [Fact]
        public void ChallengeTest()
        {
            // TODO unit test for the property 'Challenge'
        }
        /// <summary>
        /// Test the property 'Pubkey'
        /// </summary>
        [Fact]
        public void PubkeyTest()
        {
            // TODO unit test for the property 'Pubkey'
        }
        /// <summary>
        /// Test the property 'Proof'
        /// </summary>
        [Fact]
        public void ProofTest()
        {
            // TODO unit test for the property 'Proof'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

    }

}
