/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing SerializedBox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SerializedBoxTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SerializedBox
        //private SerializedBox instance;

        public SerializedBoxTests()
        {
            // TODO uncomment below to create an instance of SerializedBox
            //instance = new SerializedBox();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SerializedBox
        /// </summary>
        [Fact]
        public void SerializedBoxInstanceTest()
        {
            // TODO uncomment below to test "IsType" SerializedBox
            //Assert.IsType<SerializedBox>(instance);
        }


        /// <summary>
        /// Test the property 'BoxId'
        /// </summary>
        [Fact]
        public void BoxIdTest()
        {
            // TODO unit test for the property 'BoxId'
        }
        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Fact]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }

    }

}
