/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionHintsBag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionHintsBagTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionHintsBag
        //private TransactionHintsBag instance;

        public TransactionHintsBagTests()
        {
            // TODO uncomment below to create an instance of TransactionHintsBag
            //instance = new TransactionHintsBag();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionHintsBag
        /// </summary>
        [Fact]
        public void TransactionHintsBagInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionHintsBag
            //Assert.IsType<TransactionHintsBag>(instance);
        }


        /// <summary>
        /// Test the property 'SecretHints'
        /// </summary>
        [Fact]
        public void SecretHintsTest()
        {
            // TODO unit test for the property 'SecretHints'
        }
        /// <summary>
        /// Test the property 'PublicHints'
        /// </summary>
        [Fact]
        public void PublicHintsTest()
        {
            // TODO unit test for the property 'PublicHints'
        }

    }

}
