/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing UnsignedErgoTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnsignedErgoTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnsignedErgoTransaction
        //private UnsignedErgoTransaction instance;

        public UnsignedErgoTransactionTests()
        {
            // TODO uncomment below to create an instance of UnsignedErgoTransaction
            //instance = new UnsignedErgoTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnsignedErgoTransaction
        /// </summary>
        [Fact]
        public void UnsignedErgoTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnsignedErgoTransaction
            //Assert.IsType<UnsignedErgoTransaction>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Fact]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'DataInputs'
        /// </summary>
        [Fact]
        public void DataInputsTest()
        {
            // TODO unit test for the property 'DataInputs'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Fact]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }

    }

}
