/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ErgoNode.Api;
using ErgoNode.Model;
using ErgoNode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ErgoNode.Test.Model
{
    /// <summary>
    ///  Class for testing WorkMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkMessage
        //private WorkMessage instance;

        public WorkMessageTests()
        {
            // TODO uncomment below to create an instance of WorkMessage
            //instance = new WorkMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkMessage
        /// </summary>
        [Fact]
        public void WorkMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkMessage
            //Assert.IsType<WorkMessage>(instance);
        }


        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Fact]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }
        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }
        /// <summary>
        /// Test the property 'Pk'
        /// </summary>
        [Fact]
        public void PkTest()
        {
            // TODO unit test for the property 'Pk'
        }
        /// <summary>
        /// Test the property 'Proof'
        /// </summary>
        [Fact]
        public void ProofTest()
        {
            // TODO unit test for the property 'Proof'
        }

    }

}
