/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ErgoNode.Client.OpenAPIDateConverter;

namespace ErgoNode.Model
{
    /// <summary>
    /// BlockHeaderWithoutPow
    /// </summary>
    [DataContract(Name = "BlockHeaderWithoutPow")]
    public partial class BlockHeaderWithoutPow : IEquatable<BlockHeaderWithoutPow>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockHeaderWithoutPow" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BlockHeaderWithoutPow() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockHeaderWithoutPow" /> class.
        /// </summary>
        /// <param name="id">Base16-encoded 32 byte modifier id (required).</param>
        /// <param name="timestamp">Basic timestamp definition (required).</param>
        /// <param name="version">Ergo blockchain protocol version (required).</param>
        /// <param name="adProofsRoot">Base16-encoded 32 byte digest (required).</param>
        /// <param name="stateRoot">Base16-encoded 33 byte digest - digest with extra byte with tree height (required).</param>
        /// <param name="transactionsRoot">Base16-encoded 32 byte digest (required).</param>
        /// <param name="nBits">nBits (required).</param>
        /// <param name="extensionHash">Base16-encoded 32 byte digest (required).</param>
        /// <param name="height">height (required).</param>
        /// <param name="difficulty">difficulty (required).</param>
        /// <param name="parentId">Base16-encoded 32 byte modifier id (required).</param>
        /// <param name="votes">Base16-encoded votes for a soft-fork and parameters (required).</param>
        /// <param name="size">Size in bytes.</param>
        /// <param name="extensionId">Base16-encoded 32 byte modifier id.</param>
        /// <param name="transactionsId">Base16-encoded 32 byte modifier id.</param>
        /// <param name="adProofsId">Base16-encoded 32 byte modifier id.</param>
        public BlockHeaderWithoutPow(string id = default(string), long timestamp = default(long), int version = default(int), string adProofsRoot = default(string), string stateRoot = default(string), string transactionsRoot = default(string), long nBits = default(long), string extensionHash = default(string), int height = default(int), int difficulty = default(int), string parentId = default(string), string votes = default(string), int size = default(int), string extensionId = default(string), string transactionsId = default(string), string adProofsId = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null) {
                throw new ArgumentNullException("id is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.Id = id;
            this.Timestamp = timestamp;
            this._Version = version;
            // to ensure "adProofsRoot" is required (not null)
            if (adProofsRoot == null) {
                throw new ArgumentNullException("adProofsRoot is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.AdProofsRoot = adProofsRoot;
            // to ensure "stateRoot" is required (not null)
            if (stateRoot == null) {
                throw new ArgumentNullException("stateRoot is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.StateRoot = stateRoot;
            // to ensure "transactionsRoot" is required (not null)
            if (transactionsRoot == null) {
                throw new ArgumentNullException("transactionsRoot is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.TransactionsRoot = transactionsRoot;
            this.NBits = nBits;
            // to ensure "extensionHash" is required (not null)
            if (extensionHash == null) {
                throw new ArgumentNullException("extensionHash is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.ExtensionHash = extensionHash;
            this.Height = height;
            this.Difficulty = difficulty;
            // to ensure "parentId" is required (not null)
            if (parentId == null) {
                throw new ArgumentNullException("parentId is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.ParentId = parentId;
            // to ensure "votes" is required (not null)
            if (votes == null) {
                throw new ArgumentNullException("votes is a required property for BlockHeaderWithoutPow and cannot be null");
            }
            this.Votes = votes;
            this.Size = size;
            this.ExtensionId = extensionId;
            this.TransactionsId = transactionsId;
            this.AdProofsId = adProofsId;
        }

        /// <summary>
        /// Base16-encoded 32 byte modifier id
        /// </summary>
        /// <value>Base16-encoded 32 byte modifier id</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Basic timestamp definition
        /// </summary>
        /// <value>Basic timestamp definition</value>
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = false)]
        public long Timestamp { get; set; }

        /// <summary>
        /// Ergo blockchain protocol version
        /// </summary>
        /// <value>Ergo blockchain protocol version</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = false)]
        public int _Version { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte digest
        /// </summary>
        /// <value>Base16-encoded 32 byte digest</value>
        [DataMember(Name = "adProofsRoot", IsRequired = true, EmitDefaultValue = false)]
        public string AdProofsRoot { get; set; }

        /// <summary>
        /// Base16-encoded 33 byte digest - digest with extra byte with tree height
        /// </summary>
        /// <value>Base16-encoded 33 byte digest - digest with extra byte with tree height</value>
        [DataMember(Name = "stateRoot", IsRequired = true, EmitDefaultValue = false)]
        public string StateRoot { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte digest
        /// </summary>
        /// <value>Base16-encoded 32 byte digest</value>
        [DataMember(Name = "transactionsRoot", IsRequired = true, EmitDefaultValue = false)]
        public string TransactionsRoot { get; set; }

        /// <summary>
        /// Gets or Sets NBits
        /// </summary>
        [DataMember(Name = "nBits", IsRequired = true, EmitDefaultValue = false)]
        public long NBits { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte digest
        /// </summary>
        /// <value>Base16-encoded 32 byte digest</value>
        [DataMember(Name = "extensionHash", IsRequired = true, EmitDefaultValue = false)]
        public string ExtensionHash { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = false)]
        public int Height { get; set; }

        /// <summary>
        /// Gets or Sets Difficulty
        /// </summary>
        [DataMember(Name = "difficulty", IsRequired = true, EmitDefaultValue = false)]
        public int Difficulty { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte modifier id
        /// </summary>
        /// <value>Base16-encoded 32 byte modifier id</value>
        [DataMember(Name = "parentId", IsRequired = true, EmitDefaultValue = false)]
        public string ParentId { get; set; }

        /// <summary>
        /// Base16-encoded votes for a soft-fork and parameters
        /// </summary>
        /// <value>Base16-encoded votes for a soft-fork and parameters</value>
        [DataMember(Name = "votes", IsRequired = true, EmitDefaultValue = false)]
        public string Votes { get; set; }

        /// <summary>
        /// Size in bytes
        /// </summary>
        /// <value>Size in bytes</value>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public int Size { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte modifier id
        /// </summary>
        /// <value>Base16-encoded 32 byte modifier id</value>
        [DataMember(Name = "extensionId", EmitDefaultValue = false)]
        public string ExtensionId { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte modifier id
        /// </summary>
        /// <value>Base16-encoded 32 byte modifier id</value>
        [DataMember(Name = "transactionsId", EmitDefaultValue = false)]
        public string TransactionsId { get; set; }

        /// <summary>
        /// Base16-encoded 32 byte modifier id
        /// </summary>
        /// <value>Base16-encoded 32 byte modifier id</value>
        [DataMember(Name = "adProofsId", EmitDefaultValue = false)]
        public string AdProofsId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BlockHeaderWithoutPow {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  _Version: ").Append(_Version).Append("\n");
            sb.Append("  AdProofsRoot: ").Append(AdProofsRoot).Append("\n");
            sb.Append("  StateRoot: ").Append(StateRoot).Append("\n");
            sb.Append("  TransactionsRoot: ").Append(TransactionsRoot).Append("\n");
            sb.Append("  NBits: ").Append(NBits).Append("\n");
            sb.Append("  ExtensionHash: ").Append(ExtensionHash).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Difficulty: ").Append(Difficulty).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  Votes: ").Append(Votes).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  ExtensionId: ").Append(ExtensionId).Append("\n");
            sb.Append("  TransactionsId: ").Append(TransactionsId).Append("\n");
            sb.Append("  AdProofsId: ").Append(AdProofsId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BlockHeaderWithoutPow);
        }

        /// <summary>
        /// Returns true if BlockHeaderWithoutPow instances are equal
        /// </summary>
        /// <param name="input">Instance of BlockHeaderWithoutPow to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BlockHeaderWithoutPow input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    this.Timestamp.Equals(input.Timestamp)
                ) && 
                (
                    this._Version == input._Version ||
                    this._Version.Equals(input._Version)
                ) && 
                (
                    this.AdProofsRoot == input.AdProofsRoot ||
                    (this.AdProofsRoot != null &&
                    this.AdProofsRoot.Equals(input.AdProofsRoot))
                ) && 
                (
                    this.StateRoot == input.StateRoot ||
                    (this.StateRoot != null &&
                    this.StateRoot.Equals(input.StateRoot))
                ) && 
                (
                    this.TransactionsRoot == input.TransactionsRoot ||
                    (this.TransactionsRoot != null &&
                    this.TransactionsRoot.Equals(input.TransactionsRoot))
                ) && 
                (
                    this.NBits == input.NBits ||
                    this.NBits.Equals(input.NBits)
                ) && 
                (
                    this.ExtensionHash == input.ExtensionHash ||
                    (this.ExtensionHash != null &&
                    this.ExtensionHash.Equals(input.ExtensionHash))
                ) && 
                (
                    this.Height == input.Height ||
                    this.Height.Equals(input.Height)
                ) && 
                (
                    this.Difficulty == input.Difficulty ||
                    this.Difficulty.Equals(input.Difficulty)
                ) && 
                (
                    this.ParentId == input.ParentId ||
                    (this.ParentId != null &&
                    this.ParentId.Equals(input.ParentId))
                ) && 
                (
                    this.Votes == input.Votes ||
                    (this.Votes != null &&
                    this.Votes.Equals(input.Votes))
                ) && 
                (
                    this.Size == input.Size ||
                    this.Size.Equals(input.Size)
                ) && 
                (
                    this.ExtensionId == input.ExtensionId ||
                    (this.ExtensionId != null &&
                    this.ExtensionId.Equals(input.ExtensionId))
                ) && 
                (
                    this.TransactionsId == input.TransactionsId ||
                    (this.TransactionsId != null &&
                    this.TransactionsId.Equals(input.TransactionsId))
                ) && 
                (
                    this.AdProofsId == input.AdProofsId ||
                    (this.AdProofsId != null &&
                    this.AdProofsId.Equals(input.AdProofsId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                hashCode = hashCode * 59 + this._Version.GetHashCode();
                if (this.AdProofsRoot != null)
                    hashCode = hashCode * 59 + this.AdProofsRoot.GetHashCode();
                if (this.StateRoot != null)
                    hashCode = hashCode * 59 + this.StateRoot.GetHashCode();
                if (this.TransactionsRoot != null)
                    hashCode = hashCode * 59 + this.TransactionsRoot.GetHashCode();
                hashCode = hashCode * 59 + this.NBits.GetHashCode();
                if (this.ExtensionHash != null)
                    hashCode = hashCode * 59 + this.ExtensionHash.GetHashCode();
                hashCode = hashCode * 59 + this.Height.GetHashCode();
                hashCode = hashCode * 59 + this.Difficulty.GetHashCode();
                if (this.ParentId != null)
                    hashCode = hashCode * 59 + this.ParentId.GetHashCode();
                if (this.Votes != null)
                    hashCode = hashCode * 59 + this.Votes.GetHashCode();
                hashCode = hashCode * 59 + this.Size.GetHashCode();
                if (this.ExtensionId != null)
                    hashCode = hashCode * 59 + this.ExtensionId.GetHashCode();
                if (this.TransactionsId != null)
                    hashCode = hashCode * 59 + this.TransactionsId.GetHashCode();
                if (this.AdProofsId != null)
                    hashCode = hashCode * 59 + this.AdProofsId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // NBits (long) minimum
            if(this.NBits < (long)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NBits, must be a value greater than or equal to 0.", new [] { "NBits" });
            }

            // Height (int) minimum
            if(this.Height < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Height, must be a value greater than or equal to 0.", new [] { "Height" });
            }

            // Difficulty (int) minimum
            if(this.Difficulty < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Difficulty, must be a value greater than or equal to 0.", new [] { "Difficulty" });
            }

            yield break;
        }
    }

}
