/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ErgoNode.Client.OpenAPIDateConverter;

namespace ErgoNode.Model
{
    /// <summary>
    /// ContainsAssetPredicate
    /// </summary>
    [DataContract(Name = "ContainsAssetPredicate")]
    public partial class ContainsAssetPredicate : IEquatable<ContainsAssetPredicate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContainsAssetPredicate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContainsAssetPredicate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContainsAssetPredicate" /> class.
        /// </summary>
        /// <param name="predicate">predicate (required).</param>
        /// <param name="assetId">assetId.</param>
        public ContainsAssetPredicate(string predicate = default(string), string assetId = default(string))
        {
            // to ensure "predicate" is required (not null)
            if (predicate == null) {
                throw new ArgumentNullException("predicate is a required property for ContainsAssetPredicate and cannot be null");
            }
            this.Predicate = predicate;
            this.AssetId = assetId;
        }

        /// <summary>
        /// Gets or Sets Predicate
        /// </summary>
        [DataMember(Name = "predicate", IsRequired = true, EmitDefaultValue = false)]
        public string Predicate { get; set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [DataMember(Name = "assetId", EmitDefaultValue = false)]
        public string AssetId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContainsAssetPredicate {\n");
            sb.Append("  Predicate: ").Append(Predicate).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ContainsAssetPredicate);
        }

        /// <summary>
        /// Returns true if ContainsAssetPredicate instances are equal
        /// </summary>
        /// <param name="input">Instance of ContainsAssetPredicate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContainsAssetPredicate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Predicate == input.Predicate ||
                    (this.Predicate != null &&
                    this.Predicate.Equals(input.Predicate))
                ) && 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Predicate != null)
                    hashCode = hashCode * 59 + this.Predicate.GetHashCode();
                if (this.AssetId != null)
                    hashCode = hashCode * 59 + this.AssetId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
