/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ErgoNode.Client.OpenAPIDateConverter;

namespace ErgoNode.Model
{
    /// <summary>
    /// ErgoTransactionInput
    /// </summary>
    [DataContract(Name = "ErgoTransactionInput")]
    public partial class ErgoTransactionInput : IEquatable<ErgoTransactionInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErgoTransactionInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErgoTransactionInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErgoTransactionInput" /> class.
        /// </summary>
        /// <param name="boxId">Base16-encoded transaction box id bytes. Should be 32 bytes long (required).</param>
        /// <param name="spendingProof">spendingProof (required).</param>
        /// <param name="extension">extension.</param>
        public ErgoTransactionInput(string boxId = default(string), SpendingProof spendingProof = default(SpendingProof), Dictionary<string, string> extension = default(Dictionary<string, string>))
        {
            // to ensure "boxId" is required (not null)
            if (boxId == null) {
                throw new ArgumentNullException("boxId is a required property for ErgoTransactionInput and cannot be null");
            }
            this.BoxId = boxId;
            // to ensure "spendingProof" is required (not null)
            if (spendingProof == null) {
                throw new ArgumentNullException("spendingProof is a required property for ErgoTransactionInput and cannot be null");
            }
            this.SpendingProof = spendingProof;
            this.Extension = extension;
        }

        /// <summary>
        /// Base16-encoded transaction box id bytes. Should be 32 bytes long
        /// </summary>
        /// <value>Base16-encoded transaction box id bytes. Should be 32 bytes long</value>
        [DataMember(Name = "boxId", IsRequired = true, EmitDefaultValue = false)]
        public string BoxId { get; set; }

        /// <summary>
        /// Gets or Sets SpendingProof
        /// </summary>
        [DataMember(Name = "spendingProof", IsRequired = true, EmitDefaultValue = false)]
        public SpendingProof SpendingProof { get; set; }

        /// <summary>
        /// Gets or Sets Extension
        /// </summary>
        [DataMember(Name = "extension", EmitDefaultValue = false)]
        public Dictionary<string, string> Extension { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErgoTransactionInput {\n");
            sb.Append("  BoxId: ").Append(BoxId).Append("\n");
            sb.Append("  SpendingProof: ").Append(SpendingProof).Append("\n");
            sb.Append("  Extension: ").Append(Extension).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ErgoTransactionInput);
        }

        /// <summary>
        /// Returns true if ErgoTransactionInput instances are equal
        /// </summary>
        /// <param name="input">Instance of ErgoTransactionInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErgoTransactionInput input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BoxId == input.BoxId ||
                    (this.BoxId != null &&
                    this.BoxId.Equals(input.BoxId))
                ) && 
                (
                    this.SpendingProof == input.SpendingProof ||
                    (this.SpendingProof != null &&
                    this.SpendingProof.Equals(input.SpendingProof))
                ) && 
                (
                    this.Extension == input.Extension ||
                    this.Extension != null &&
                    input.Extension != null &&
                    this.Extension.SequenceEqual(input.Extension)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BoxId != null)
                    hashCode = hashCode * 59 + this.BoxId.GetHashCode();
                if (this.SpendingProof != null)
                    hashCode = hashCode * 59 + this.SpendingProof.GetHashCode();
                if (this.Extension != null)
                    hashCode = hashCode * 59 + this.Extension.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
