/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ErgoNode.Client.OpenAPIDateConverter;

namespace ErgoNode.Model
{
    /// <summary>
    /// InlineObject1
    /// </summary>
    [DataContract(Name = "inline_object_1")]
    public partial class InlineObject1 : IEquatable<InlineObject1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineObject1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject1" /> class.
        /// </summary>
        /// <param name="pass">Password to encrypt wallet file with (required).</param>
        /// <param name="mnemonic">Mnemonic seed (required).</param>
        /// <param name="mnemonicPass">Optional pass to password-protect mnemonic seed.</param>
        public InlineObject1(string pass = default(string), string mnemonic = default(string), string mnemonicPass = default(string))
        {
            // to ensure "pass" is required (not null)
            if (pass == null) {
                throw new ArgumentNullException("pass is a required property for InlineObject1 and cannot be null");
            }
            this.Pass = pass;
            // to ensure "mnemonic" is required (not null)
            if (mnemonic == null) {
                throw new ArgumentNullException("mnemonic is a required property for InlineObject1 and cannot be null");
            }
            this.Mnemonic = mnemonic;
            this.MnemonicPass = mnemonicPass;
        }

        /// <summary>
        /// Password to encrypt wallet file with
        /// </summary>
        /// <value>Password to encrypt wallet file with</value>
        [DataMember(Name = "pass", IsRequired = true, EmitDefaultValue = false)]
        public string Pass { get; set; }

        /// <summary>
        /// Mnemonic seed
        /// </summary>
        /// <value>Mnemonic seed</value>
        [DataMember(Name = "mnemonic", IsRequired = true, EmitDefaultValue = false)]
        public string Mnemonic { get; set; }

        /// <summary>
        /// Optional pass to password-protect mnemonic seed
        /// </summary>
        /// <value>Optional pass to password-protect mnemonic seed</value>
        [DataMember(Name = "mnemonicPass", EmitDefaultValue = false)]
        public string MnemonicPass { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject1 {\n");
            sb.Append("  Pass: ").Append(Pass).Append("\n");
            sb.Append("  Mnemonic: ").Append(Mnemonic).Append("\n");
            sb.Append("  MnemonicPass: ").Append(MnemonicPass).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineObject1);
        }

        /// <summary>
        /// Returns true if InlineObject1 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineObject1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject1 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pass == input.Pass ||
                    (this.Pass != null &&
                    this.Pass.Equals(input.Pass))
                ) && 
                (
                    this.Mnemonic == input.Mnemonic ||
                    (this.Mnemonic != null &&
                    this.Mnemonic.Equals(input.Mnemonic))
                ) && 
                (
                    this.MnemonicPass == input.MnemonicPass ||
                    (this.MnemonicPass != null &&
                    this.MnemonicPass.Equals(input.MnemonicPass))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pass != null)
                    hashCode = hashCode * 59 + this.Pass.GetHashCode();
                if (this.Mnemonic != null)
                    hashCode = hashCode * 59 + this.Mnemonic.GetHashCode();
                if (this.MnemonicPass != null)
                    hashCode = hashCode * 59 + this.MnemonicPass.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
