/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ErgoNode.Client.OpenAPIDateConverter;

namespace ErgoNode.Model
{
    /// <summary>
    /// ScanIdBoxId
    /// </summary>
    [DataContract(Name = "ScanIdBoxId")]
    public partial class ScanIdBoxId : IEquatable<ScanIdBoxId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScanIdBoxId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScanIdBoxId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScanIdBoxId" /> class.
        /// </summary>
        /// <param name="scanId">scanId (required).</param>
        /// <param name="boxId">Base16-encoded transaction box id bytes. Should be 32 bytes long (required).</param>
        public ScanIdBoxId(int scanId = default(int), string boxId = default(string))
        {
            this.ScanId = scanId;
            // to ensure "boxId" is required (not null)
            if (boxId == null) {
                throw new ArgumentNullException("boxId is a required property for ScanIdBoxId and cannot be null");
            }
            this.BoxId = boxId;
        }

        /// <summary>
        /// Gets or Sets ScanId
        /// </summary>
        [DataMember(Name = "scanId", IsRequired = true, EmitDefaultValue = false)]
        public int ScanId { get; set; }

        /// <summary>
        /// Base16-encoded transaction box id bytes. Should be 32 bytes long
        /// </summary>
        /// <value>Base16-encoded transaction box id bytes. Should be 32 bytes long</value>
        [DataMember(Name = "boxId", IsRequired = true, EmitDefaultValue = false)]
        public string BoxId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScanIdBoxId {\n");
            sb.Append("  ScanId: ").Append(ScanId).Append("\n");
            sb.Append("  BoxId: ").Append(BoxId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScanIdBoxId);
        }

        /// <summary>
        /// Returns true if ScanIdBoxId instances are equal
        /// </summary>
        /// <param name="input">Instance of ScanIdBoxId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScanIdBoxId input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ScanId == input.ScanId ||
                    this.ScanId.Equals(input.ScanId)
                ) && 
                (
                    this.BoxId == input.BoxId ||
                    (this.BoxId != null &&
                    this.BoxId.Equals(input.BoxId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.ScanId.GetHashCode();
                if (this.BoxId != null)
                    hashCode = hashCode * 59 + this.BoxId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
