/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.15
 * Contact: ergoplatform@protonmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ErgoNode.Client.OpenAPIDateConverter;

namespace ErgoNode.Model
{
    /// <summary>
    /// SerializedBox
    /// </summary>
    [DataContract(Name = "SerializedBox")]
    public partial class SerializedBox : IEquatable<SerializedBox>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SerializedBox" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SerializedBox() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SerializedBox" /> class.
        /// </summary>
        /// <param name="boxId">Base16-encoded transaction box id bytes. Should be 32 bytes long (required).</param>
        /// <param name="bytes">Base16-encoded bytes (required).</param>
        public SerializedBox(string boxId = default(string), string bytes = default(string))
        {
            // to ensure "boxId" is required (not null)
            if (boxId == null) {
                throw new ArgumentNullException("boxId is a required property for SerializedBox and cannot be null");
            }
            this.BoxId = boxId;
            // to ensure "bytes" is required (not null)
            if (bytes == null) {
                throw new ArgumentNullException("bytes is a required property for SerializedBox and cannot be null");
            }
            this.Bytes = bytes;
        }

        /// <summary>
        /// Base16-encoded transaction box id bytes. Should be 32 bytes long
        /// </summary>
        /// <value>Base16-encoded transaction box id bytes. Should be 32 bytes long</value>
        [DataMember(Name = "boxId", IsRequired = true, EmitDefaultValue = false)]
        public string BoxId { get; set; }

        /// <summary>
        /// Base16-encoded bytes
        /// </summary>
        /// <value>Base16-encoded bytes</value>
        [DataMember(Name = "bytes", IsRequired = true, EmitDefaultValue = false)]
        public string Bytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SerializedBox {\n");
            sb.Append("  BoxId: ").Append(BoxId).Append("\n");
            sb.Append("  Bytes: ").Append(Bytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SerializedBox);
        }

        /// <summary>
        /// Returns true if SerializedBox instances are equal
        /// </summary>
        /// <param name="input">Instance of SerializedBox to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SerializedBox input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BoxId == input.BoxId ||
                    (this.BoxId != null &&
                    this.BoxId.Equals(input.BoxId))
                ) && 
                (
                    this.Bytes == input.Bytes ||
                    (this.Bytes != null &&
                    this.Bytes.Equals(input.Bytes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BoxId != null)
                    hashCode = hashCode * 59 + this.BoxId.GetHashCode();
                if (this.Bytes != null)
                    hashCode = hashCode * 59 + this.Bytes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
