"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pow_solutions import PowSolutions
globals()['PowSolutions'] = PowSolutions
from openapi_client.model.block_header import BlockHeader


class TestBlockHeader(unittest.TestCase):
    """BlockHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockHeader(self):
        """Test BlockHeader"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockHeader()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
