"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.merkle_proof import MerkleProof


class TestMerkleProof(unittest.TestCase):
    """MerkleProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMerkleProof(self):
        """Test MerkleProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MerkleProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
