"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.int64 import Int64
from openapi_client.model.registers import Registers
globals()['Int64'] = Int64
globals()['Registers'] = Registers
from openapi_client.model.asset_issue_request import AssetIssueRequest


class TestAssetIssueRequest(unittest.TestCase):
    """AssetIssueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetIssueRequest(self):
        """Test AssetIssueRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetIssueRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
