"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ergo_transaction_data_input import ErgoTransactionDataInput
from openapi_client.model.ergo_transaction_input import ErgoTransactionInput
from openapi_client.model.ergo_transaction_output import ErgoTransactionOutput
globals()['ErgoTransactionDataInput'] = ErgoTransactionDataInput
globals()['ErgoTransactionInput'] = ErgoTransactionInput
globals()['ErgoTransactionOutput'] = ErgoTransactionOutput
from openapi_client.model.ergo_like_transaction import ErgoLikeTransaction


class TestErgoLikeTransaction(unittest.TestCase):
    """ErgoLikeTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErgoLikeTransaction(self):
        """Test ErgoLikeTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErgoLikeTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
