"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.nipopow_api import NipopowApi  # noqa: E501


class TestNipopowApi(unittest.TestCase):
    """NipopowApi unit test stubs"""

    def setUp(self):
        self.api = NipopowApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_popow_header_by_height(self):
        """Test case for get_popow_header_by_height

        Construct PoPow header for best header at given height  # noqa: E501
        """
        pass

    def test_get_popow_header_by_id(self):
        """Test case for get_popow_header_by_id

        Construct PoPow header according to given header id  # noqa: E501
        """
        pass

    def test_get_popow_proof(self):
        """Test case for get_popow_proof

        Construct PoPoW proof for given min superchain length and suffix length  # noqa: E501
        """
        pass

    def test_get_popow_proof_by_header_id(self):
        """Test case for get_popow_proof_by_header_id

        Construct PoPoW proof for given min superchain length, suffix length and header ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
