"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.contains_predicate_all_of import ContainsPredicateAllOf


class TestContainsPredicateAllOf(unittest.TestCase):
    """ContainsPredicateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainsPredicateAllOf(self):
        """Test ContainsPredicateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainsPredicateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
