"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.block_ad_proofs import BlockADProofs


class TestBlockADProofs(unittest.TestCase):
    """BlockADProofs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockADProofs(self):
        """Test BlockADProofs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockADProofs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
