"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.utils_api import UtilsApi  # noqa: E501


class TestUtilsApi(unittest.TestCase):
    """UtilsApi unit test stubs"""

    def setUp(self):
        self.api = UtilsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_address_to_raw(self):
        """Test case for address_to_raw

        Convert Pay-To-Public-Key Address to raw representation (hex-encoded serialized curve point)  # noqa: E501
        """
        pass

    def test_check_address_validity(self):
        """Test case for check_address_validity

        Check address validity  # noqa: E501
        """
        pass

    def test_ergo_tree_to_address(self):
        """Test case for ergo_tree_to_address

        Generate Ergo address from hex-encoded ErgoTree  # noqa: E501
        """
        pass

    def test_get_random_seed(self):
        """Test case for get_random_seed

        Get random seed of 32 bytes  # noqa: E501
        """
        pass

    def test_get_random_seed_with_length(self):
        """Test case for get_random_seed_with_length

        Generate random seed of specified length in bytes  # noqa: E501
        """
        pass

    def test_hash_blake2b(self):
        """Test case for hash_blake2b

        Return Blake2b hash of specified message  # noqa: E501
        """
        pass

    def test_raw_to_address(self):
        """Test case for raw_to_address

        Generate Pay-To-Public-Key address from hex-encoded raw pubkey (secp256k1 serialized point)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
