"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.inline_response2006 import InlineResponse2006


class TestInlineResponse2006(unittest.TestCase):
    """InlineResponse2006 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006(self):
        """Test InlineResponse2006"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
