"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.transaction_hints_bag import TransactionHintsBag
from openapi_client.model.transaction_signing_request_secrets import TransactionSigningRequestSecrets
from openapi_client.model.unsigned_ergo_transaction import UnsignedErgoTransaction
globals()['TransactionHintsBag'] = TransactionHintsBag
globals()['TransactionSigningRequestSecrets'] = TransactionSigningRequestSecrets
globals()['UnsignedErgoTransaction'] = UnsignedErgoTransaction
from openapi_client.model.transaction_signing_request import TransactionSigningRequest


class TestTransactionSigningRequest(unittest.TestCase):
    """TransactionSigningRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSigningRequest(self):
        """Test TransactionSigningRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionSigningRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
