"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.generate_commitments_request_secrets import GenerateCommitmentsRequestSecrets
from openapi_client.model.unsigned_ergo_transaction import UnsignedErgoTransaction
globals()['GenerateCommitmentsRequestSecrets'] = GenerateCommitmentsRequestSecrets
globals()['UnsignedErgoTransaction'] = UnsignedErgoTransaction
from openapi_client.model.generate_commitments_request import GenerateCommitmentsRequest


class TestGenerateCommitmentsRequest(unittest.TestCase):
    """GenerateCommitmentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenerateCommitmentsRequest(self):
        """Test GenerateCommitmentsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenerateCommitmentsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
