"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scanning_predicate import ScanningPredicate
globals()['ScanningPredicate'] = ScanningPredicate
from openapi_client.model.scan_request import ScanRequest


class TestScanRequest(unittest.TestCase):
    """ScanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScanRequest(self):
        """Test ScanRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScanRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
