"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.block_header_without_pow import BlockHeaderWithoutPow


class TestBlockHeaderWithoutPow(unittest.TestCase):
    """BlockHeaderWithoutPow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockHeaderWithoutPow(self):
        """Test BlockHeaderWithoutPow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockHeaderWithoutPow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
