"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.scan_api import ScanApi  # noqa: E501


class TestScanApi(unittest.TestCase):
    """ScanApi unit test stubs"""

    def setUp(self):
        self.api = ScanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_box(self):
        """Test case for add_box

        Adds a box to scans, writes box to database if it is not there. You can use scan number 10 to add a box to the wallet.  # noqa: E501
        """
        pass

    def test_deregister_scan(self):
        """Test case for deregister_scan

        Stop tracking and deregister scan  # noqa: E501
        """
        pass

    def test_list_all_scans(self):
        """Test case for list_all_scans

        List all the registered scans  # noqa: E501
        """
        pass

    def test_list_unspent_scans(self):
        """Test case for list_unspent_scans

        List boxes which are not spent.  # noqa: E501
        """
        pass

    def test_register_scan(self):
        """Test case for register_scan

        Register a scan  # noqa: E501
        """
        pass

    def test_scan_stop_tracking(self):
        """Test case for scan_stop_tracking

        Stop scan-related box tracking  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
