"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ergo_transaction_data_input import ErgoTransactionDataInput
from openapi_client.model.ergo_transaction_output import ErgoTransactionOutput
from openapi_client.model.ergo_transaction_unsigned_input import ErgoTransactionUnsignedInput
globals()['ErgoTransactionDataInput'] = ErgoTransactionDataInput
globals()['ErgoTransactionOutput'] = ErgoTransactionOutput
globals()['ErgoTransactionUnsignedInput'] = ErgoTransactionUnsignedInput
from openapi_client.model.unsigned_ergo_transaction import UnsignedErgoTransaction


class TestUnsignedErgoTransaction(unittest.TestCase):
    """UnsignedErgoTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnsignedErgoTransaction(self):
        """Test UnsignedErgoTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnsignedErgoTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
