"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ergo_transaction_output import ErgoTransactionOutput
globals()['ErgoTransactionOutput'] = ErgoTransactionOutput
from openapi_client.model.scan_ids_box import ScanIdsBox


class TestScanIdsBox(unittest.TestCase):
    """ScanIdsBox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScanIdsBox(self):
        """Test ScanIdsBox"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScanIdsBox()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
