"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.contains_predicate_all_of import ContainsPredicateAllOf
from openapi_client.model.scanning_predicate import ScanningPredicate
globals()['ContainsPredicateAllOf'] = ContainsPredicateAllOf
globals()['ScanningPredicate'] = ScanningPredicate
from openapi_client.model.contains_predicate import ContainsPredicate


class TestContainsPredicate(unittest.TestCase):
    """ContainsPredicate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainsPredicate(self):
        """Test ContainsPredicate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContainsPredicate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
