"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sigma_boolean import SigmaBoolean
from openapi_client.model.sigma_boolean_and_predicate_all_of import SigmaBooleanAndPredicateAllOf
globals()['SigmaBoolean'] = SigmaBoolean
globals()['SigmaBooleanAndPredicateAllOf'] = SigmaBooleanAndPredicateAllOf
from openapi_client.model.sigma_boolean_or_predicate import SigmaBooleanOrPredicate


class TestSigmaBooleanOrPredicate(unittest.TestCase):
    """SigmaBooleanOrPredicate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSigmaBooleanOrPredicate(self):
        """Test SigmaBooleanOrPredicate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SigmaBooleanOrPredicate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
