"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.avl_tree_data import AvlTreeData
from openapi_client.model.ergo_like_transaction import ErgoLikeTransaction
from openapi_client.model.ergo_transaction_output import ErgoTransactionOutput
from openapi_client.model.pre_header import PreHeader
from openapi_client.model.sigma_header import SigmaHeader
globals()['AvlTreeData'] = AvlTreeData
globals()['ErgoLikeTransaction'] = ErgoLikeTransaction
globals()['ErgoTransactionOutput'] = ErgoTransactionOutput
globals()['PreHeader'] = PreHeader
globals()['SigmaHeader'] = SigmaHeader
from openapi_client.model.ergo_like_context import ErgoLikeContext


class TestErgoLikeContext(unittest.TestCase):
    """ErgoLikeContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErgoLikeContext(self):
        """Test ErgoLikeContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErgoLikeContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
