"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ergo_node.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from ergo_node.exceptions import ApiAttributeError


def lazy_import():
    from ergo_node.model.avl_tree_data import AvlTreeData
    from ergo_node.model.ergo_like_transaction import ErgoLikeTransaction
    from ergo_node.model.ergo_transaction_output import ErgoTransactionOutput
    from ergo_node.model.pre_header import PreHeader
    from ergo_node.model.sigma_header import SigmaHeader
    globals()['AvlTreeData'] = AvlTreeData
    globals()['ErgoLikeTransaction'] = ErgoLikeTransaction
    globals()['ErgoTransactionOutput'] = ErgoTransactionOutput
    globals()['PreHeader'] = PreHeader
    globals()['SigmaHeader'] = SigmaHeader


class ErgoLikeContext(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'last_block_utxo_root': (AvlTreeData,),  # noqa: E501
            'headers': ([SigmaHeader],),  # noqa: E501
            'pre_header': (PreHeader,),  # noqa: E501
            'data_boxes': ([ErgoTransactionOutput],),  # noqa: E501
            'boxes_to_spend': ([ErgoTransactionOutput],),  # noqa: E501
            'spending_transaction': (ErgoLikeTransaction,),  # noqa: E501
            'self_index': (int,),  # noqa: E501
            'extension': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'validation_settings': (str,),  # noqa: E501
            'cost_limit': (int,),  # noqa: E501
            'init_cost': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'last_block_utxo_root': 'lastBlockUtxoRoot',  # noqa: E501
        'headers': 'headers',  # noqa: E501
        'pre_header': 'preHeader',  # noqa: E501
        'data_boxes': 'dataBoxes',  # noqa: E501
        'boxes_to_spend': 'boxesToSpend',  # noqa: E501
        'spending_transaction': 'spendingTransaction',  # noqa: E501
        'self_index': 'selfIndex',  # noqa: E501
        'extension': 'extension',  # noqa: E501
        'validation_settings': 'validationSettings',  # noqa: E501
        'cost_limit': 'costLimit',  # noqa: E501
        'init_cost': 'initCost',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, last_block_utxo_root, headers, pre_header, data_boxes, boxes_to_spend, spending_transaction, self_index, extension, validation_settings, cost_limit, init_cost, *args, **kwargs):  # noqa: E501
        """ErgoLikeContext - a model defined in OpenAPI

        Args:
            last_block_utxo_root (AvlTreeData):
            headers ([SigmaHeader]): fixed number of last block headers in descending order (first header is the newest one)
            pre_header (PreHeader):
            data_boxes ([ErgoTransactionOutput]): boxes, that corresponds to id's of `spendingTransaction.dataInputs`
            boxes_to_spend ([ErgoTransactionOutput]): boxes, that corresponds to id's of `spendingTransaction.inputs`
            spending_transaction (ErgoLikeTransaction):
            self_index (int): index of the box in `boxesToSpend` that contains the script we're evaluating
            extension ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): prover-defined key-value pairs, that may be used inside a script
            validation_settings (str): validation parameters passed to Interpreter.verify to detect soft-fork conditions
            cost_limit (int): hard limit on accumulated execution cost, if exceeded lead to CostLimitException to be thrown
            init_cost (int): initial value of execution cost already accumulated before Interpreter.verify is called

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.last_block_utxo_root = last_block_utxo_root
        self.headers = headers
        self.pre_header = pre_header
        self.data_boxes = data_boxes
        self.boxes_to_spend = boxes_to_spend
        self.spending_transaction = spending_transaction
        self.self_index = self_index
        self.extension = extension
        self.validation_settings = validation_settings
        self.cost_limit = cost_limit
        self.init_cost = init_cost
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, last_block_utxo_root, headers, pre_header, data_boxes, boxes_to_spend, spending_transaction, self_index, extension, validation_settings, cost_limit, init_cost, *args, **kwargs):  # noqa: E501
        """ErgoLikeContext - a model defined in OpenAPI

        Args:
            last_block_utxo_root (AvlTreeData):
            headers ([SigmaHeader]): fixed number of last block headers in descending order (first header is the newest one)
            pre_header (PreHeader):
            data_boxes ([ErgoTransactionOutput]): boxes, that corresponds to id's of `spendingTransaction.dataInputs`
            boxes_to_spend ([ErgoTransactionOutput]): boxes, that corresponds to id's of `spendingTransaction.inputs`
            spending_transaction (ErgoLikeTransaction):
            self_index (int): index of the box in `boxesToSpend` that contains the script we're evaluating
            extension ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): prover-defined key-value pairs, that may be used inside a script
            validation_settings (str): validation parameters passed to Interpreter.verify to detect soft-fork conditions
            cost_limit (int): hard limit on accumulated execution cost, if exceeded lead to CostLimitException to be thrown
            init_cost (int): initial value of execution cost already accumulated before Interpreter.verify is called

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.last_block_utxo_root = last_block_utxo_root
        self.headers = headers
        self.pre_header = pre_header
        self.data_boxes = data_boxes
        self.boxes_to_spend = boxes_to_spend
        self.spending_transaction = spending_transaction
        self.self_index = self_index
        self.extension = extension
        self.validation_settings = validation_settings
        self.cost_limit = cost_limit
        self.init_cost = init_cost
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
