"""
    Ergo Node API

    API docs for Ergo Node. Models are shared between all Ergo products  # noqa: E501

    The version of the OpenAPI document: 4.0.15
    Contact: ergoplatform@protonmail.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ergo_node.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from ergo_node.exceptions import ApiAttributeError


def lazy_import():
    from ergo_node.model.ergo_transaction_output import ErgoTransactionOutput
    globals()['ErgoTransactionOutput'] = ErgoTransactionOutput


class WalletBox(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('confirmations_num',): {
            'inclusive_minimum': 0,
        },
        ('spending_height',): {
            'inclusive_minimum': 0,
        },
        ('inclusion_height',): {
            'inclusive_minimum': 0,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'box': (ErgoTransactionOutput,),  # noqa: E501
            'confirmations_num': (int, none_type,),  # noqa: E501
            'address': (str,),  # noqa: E501
            'creation_transaction': (str,),  # noqa: E501
            'spending_transaction': (str,),  # noqa: E501
            'spending_height': (int, none_type,),  # noqa: E501
            'inclusion_height': (int,),  # noqa: E501
            'onchain': (bool,),  # noqa: E501
            'spent': (bool,),  # noqa: E501
            'creation_out_index': (int,),  # noqa: E501
            'scans': ([int],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'box': 'box',  # noqa: E501
        'confirmations_num': 'confirmationsNum',  # noqa: E501
        'address': 'address',  # noqa: E501
        'creation_transaction': 'creationTransaction',  # noqa: E501
        'spending_transaction': 'spendingTransaction',  # noqa: E501
        'spending_height': 'spendingHeight',  # noqa: E501
        'inclusion_height': 'inclusionHeight',  # noqa: E501
        'onchain': 'onchain',  # noqa: E501
        'spent': 'spent',  # noqa: E501
        'creation_out_index': 'creationOutIndex',  # noqa: E501
        'scans': 'scans',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, box, confirmations_num, address, creation_transaction, spending_transaction, spending_height, inclusion_height, onchain, spent, creation_out_index, scans, *args, **kwargs):  # noqa: E501
        """WalletBox - a model defined in OpenAPI

        Args:
            box (ErgoTransactionOutput):
            confirmations_num (int, none_type): Number of confirmations, if the box is included into the blockchain
            address (str): Encoded Ergo Address
            creation_transaction (str): Base16-encoded 32 byte modifier id
            spending_transaction (str): Base16-encoded 32 byte modifier id
            spending_height (int, none_type): The height the box was spent at
            inclusion_height (int): The height the transaction containing the box was included in a block at
            onchain (bool): A flag signalling whether the box is created on main chain
            spent (bool): A flag signalling whether the box was spent
            creation_out_index (int): An index of a box in the creating transaction
            scans ([int]): Scan identifiers the box relates to

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.box = box
        self.confirmations_num = confirmations_num
        self.address = address
        self.creation_transaction = creation_transaction
        self.spending_transaction = spending_transaction
        self.spending_height = spending_height
        self.inclusion_height = inclusion_height
        self.onchain = onchain
        self.spent = spent
        self.creation_out_index = creation_out_index
        self.scans = scans
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, box, confirmations_num, address, creation_transaction, spending_transaction, spending_height, inclusion_height, onchain, spent, creation_out_index, scans, *args, **kwargs):  # noqa: E501
        """WalletBox - a model defined in OpenAPI

        Args:
            box (ErgoTransactionOutput):
            confirmations_num (int, none_type): Number of confirmations, if the box is included into the blockchain
            address (str): Encoded Ergo Address
            creation_transaction (str): Base16-encoded 32 byte modifier id
            spending_transaction (str): Base16-encoded 32 byte modifier id
            spending_height (int, none_type): The height the box was spent at
            inclusion_height (int): The height the transaction containing the box was included in a block at
            onchain (bool): A flag signalling whether the box is created on main chain
            spent (bool): A flag signalling whether the box was spent
            creation_out_index (int): An index of a box in the creating transaction
            scans ([int]): Scan identifiers the box relates to

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.box = box
        self.confirmations_num = confirmations_num
        self.address = address
        self.creation_transaction = creation_transaction
        self.spending_transaction = spending_transaction
        self.spending_height = spending_height
        self.inclusion_height = inclusion_height
        self.onchain = onchain
        self.spent = spent
        self.creation_out_index = creation_out_index
        self.scans = scans
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
